#!/usr/bin/env bash

# img=$(cat .cache/wal/wal) // mais tarde use isso pra colocar no feh do plano de fundo coloque no autostart.

# definindo as pastas dos programas
DWM=~/Programas/dwm/dwm-6.3/
ST=~/Programas/st-0.8.5/
DMENU=~/Programas/dwm/dmenu-5.0/
## Recompilando o DWM

cd $DWM
echo 'Recompilando o DWM'
echo "Você está em $(pwd)"
#sudo cp config.def.h config.h
sudo make clean install
echo 'Compilação terminada'

## Recompilando o ST
cd $ST
echo 'Recompilando o ST'
echo "Você está em $(pwd)"
sudo make clean install
echo 'Compilação terminada'

## Recompilando o dmenu
cd $DMENU
echo 'Recompilando o Dmenu'
echo "Você está em $(pwd)"
sudo make clean install
echo 'Compilação terminada'

echo 'Todos os programas foram recompilados, dê um restar no seu DWM para a ver as mudanças'
